# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-14 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentclasses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_name',
        ),
        migrations.RemoveField(
            model_name='student_lecture',
            name='student_lecture_name',
        ),
    ]
