# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-14 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentclasses', '0002_auto_20180314_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentlecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentlecture_name', models.CharField(default='ComputerScience Lectures', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='student_lecture',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='student_lecture',
            name='student',
        ),
        migrations.AddField(
            model_name='lecture',
            name='lecture_name',
            field=models.CharField(default='Lecture for Dragons', max_length=20),
        ),
        migrations.DeleteModel(
            name='Student_Lecture',
        ),
        migrations.AddField(
            model_name='studentlecture',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentclasses.Lecture'),
        ),
        migrations.AddField(
            model_name='studentlecture',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentclasses.Student'),
        ),
    ]
